spring.application.name=producer-app
server.port=${SERVER_PORT:8080}

app.topic=${APP_TOPIC:secure-customer-events}
app.dek.registry.topic=${APP_DEK_REGISTRY_TOPIC:_dek_registry_keys}
app.field-encryption.secret=${APP_FIELD_ENCRYPTION_SECRET:demo-field-secret-change-me}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}
spring.kafka.properties.auto.register.schemas=false
spring.kafka.properties.use.latest.version=true
spring.kafka.properties.latest.compatibility.strict=false
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer

spring.kafka.properties.rule.executors._default_.class=io.confluent.kafka.schemaregistry.encryption.FieldEncryptionExecutor
spring.kafka.properties.rule.executors._default_.param.kek.name=${APP_KEK_NAME:customer-pii-kek}
spring.kafka.properties.rule.executors._default_.param.kms.type=${APP_KMS_TYPE:aws-kms}
spring.kafka.properties.rule.executors._default_.param.kms.key.id=${APP_KMS_KEY_ID:alias/customer-pii-kek}
spring.kafka.properties.rule.executors._default_.param.kms.key.secret=${APP_KMS_KEY_SECRET:}
spring.kafka.properties.rule.executors._default_.param.kms.region=${APP_KMS_REGION:us-east-1}
spring.kafka.properties.rule.executors._default_.param.kms.endpoint=${APP_KMS_ENDPOINT:http://localstack:4566}
spring.kafka.properties.rule.executors._default_.param.kms.access.key.id=${APP_KMS_ACCESS_KEY_ID:test}
spring.kafka.properties.rule.executors._default_.param.kms.secret.access.key=${APP_KMS_SECRET_ACCESS_KEY:test}

# MinIO inbox (written by event-generator, read by Spark ingester)
app.minio.inbox.endpoint=${APP_MINIO_INBOX_ENDPOINT:http://minio:9000}
app.minio.inbox.access-key=${APP_MINIO_INBOX_ACCESS_KEY:minioadmin}
app.minio.inbox.secret-key=${APP_MINIO_INBOX_SECRET_KEY:minioadmin}
app.minio.inbox.bucket=${APP_MINIO_INBOX_BUCKET:event-inbox}

# Spark micro-batch poll interval (ms)
app.spark.micro-batch.interval-ms=${APP_SPARK_INTERVAL_MS:3000}

management.endpoints.web.exposure.include=health,info,prometheus
