FROM maven:3.9.8-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml mvnw ./
COPY .mvn .mvn
COPY common common
COPY consumer-app consumer-app
COPY producer-app producer-app
COPY event-generator event-generator
RUN chmod +x mvnw \
	&& ./mvnw -q -pl consumer-app -am -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/consumer-app/target/consumer-app-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/app.jar"]
