FROM maven:3.9.8-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml mvnw ./
COPY .mvn .mvn
COPY common common
COPY event-generator event-generator
COPY producer-app producer-app
COPY consumer-app consumer-app
RUN chmod +x mvnw \
    && ./mvnw -q -pl event-generator -am -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/event-generator/target/event-generator-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java","-jar","/app/app.jar"]
