spring.application.name=event-generator
server.port=${SERVER_PORT:8082}

app.minio.endpoint=${APP_MINIO_ENDPOINT:http://localhost:9000}
app.minio.access-key=${APP_MINIO_ACCESS_KEY:minioadmin}
app.minio.secret-key=${APP_MINIO_SECRET_KEY:minioadmin}
app.minio.bucket=${APP_MINIO_INBOX_BUCKET:event-inbox}

# How often to generate a new event (ms)
app.generator.interval-ms=${APP_GENERATOR_INTERVAL_MS:5000}

management.endpoints.web.exposure.include=health,info
